#!/bin/bash
#
# Gaming Website Creator - Main Orchestration Script
# Creates a complete gaming website with initial content
#
# Usage: ./create_gaming_website.sh <website-name> [niche]
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_DIR="$(dirname "$SCRIPT_DIR")"
ASSETS_DIR="$(dirname "$TOOLS_DIR")"
DEPLOYED_DIR="$ASSETS_DIR/websites/deployed"
TEMPLATES_DIR="$TOOLS_DIR/templates"

# Functions
print_header() {
    echo -e "${BLUE}=================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}=================================${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

# Validate arguments
if [ -z "$1" ]; then
    print_error "Website name is required"
    echo "Usage: ./create_gaming_website.sh <website-name> [niche]"
    echo ""
    echo "Examples:"
    echo "  ./create_gaming_website.sh indie-games-review"
    echo "  ./create_gaming_website.sh retro-rpg-hub rpg"
    echo "  ./create_gaming_website.sh mobile-gaming-tips mobile"
    exit 1
fi

WEBSITE_NAME="$1"
NICHE="${2:-indie}"  # Default to indie games

# Validate website name format
if [[ ! "$WEBSITE_NAME" =~ ^[a-z0-9-]+$ ]]; then
    print_error "Website name must contain only lowercase letters, numbers, and hyphens"
    exit 1
fi

# Display configuration
print_header "Gaming Website Creator"
echo ""
echo "Configuration:"
echo "  Website Name: $WEBSITE_NAME"
echo "  Gaming Niche: $NICHE"
echo "  Deploy Path:  $DEPLOYED_DIR/$WEBSITE_NAME"
echo ""

# Confirm creation
read -p "Create this website? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    print_warning "Website creation cancelled"
    exit 0
fi

# Create website directory structure
print_header "Creating Directory Structure"

WEBSITE_DIR="$DEPLOYED_DIR/$WEBSITE_NAME"

if [ -d "$WEBSITE_DIR" ]; then
    print_error "Website directory already exists: $WEBSITE_DIR"
    read -p "Delete and recreate? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$WEBSITE_DIR"
        print_success "Removed existing directory"
    else
        exit 1
    fi
fi

# Create directory structure
mkdir -p "$WEBSITE_DIR"/{config,content/{reviews,guides,top-lists,news},static/{images,css,js},templates}

print_success "Created directory structure"

# Generate website configuration
print_header "Generating Website Configuration"

"$SCRIPT_DIR/generate_site_config.sh" "$WEBSITE_NAME" "$NICHE" > "$WEBSITE_DIR/config/site.json"

print_success "Generated site.json configuration"

# Create package.json for static site
cat > "$WEBSITE_DIR/package.json" << EOF
{
  "name": "$WEBSITE_NAME",
  "version": "1.0.0",
  "description": "Gaming website - $NICHE niche",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "export": "next build && next export"
  },
  "dependencies": {
    "next": "^14.0.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.0.0",
    "typescript": "^5.0.0"
  }
}
EOF

print_success "Created package.json"

# Create README
cat > "$WEBSITE_DIR/README.md" << EOF
# $WEBSITE_NAME

Gaming website focused on: **$NICHE**

## Overview

This website was automatically generated by the Gaming Website Creator system.

**Created:** $(date +"%Y-%m-%d")
**Niche:** $NICHE
**Status:** Setup Complete

## Next Steps

1. **Generate Content**
   \`\`\`bash
   cd $SCRIPT_DIR
   ./generate_content.sh $WEBSITE_NAME 20
   \`\`\`

2. **Build Website**
   \`\`\`bash
   ./build_website.sh $WEBSITE_NAME
   \`\`\`

3. **Deploy**
   \`\`\`bash
   ./deploy_website.sh $WEBSITE_NAME netlify
   \`\`\`

## Structure

\`\`\`
$WEBSITE_NAME/
├── config/          # Site configuration
├── content/         # Markdown articles
│   ├── reviews/     # Game reviews
│   ├── guides/      # Game guides
│   ├── top-lists/   # Top 10 lists
│   └── news/        # Gaming news
├── static/          # Static assets
│   ├── images/      # Images
│   ├── css/         # Stylesheets
│   └── js/          # JavaScript
└── templates/       # Page templates
\`\`\`

## Monetization

- Google AdSense: Setup required
- Amazon Associates: Add affiliate tag
- Humble Bundle: Add affiliate ID

See \`config/site.json\` for monetization configuration.

## Analytics

- Google Analytics: Add tracking ID
- Search Console: Verify ownership

## Content Plan

Target: 20-30 initial articles
Publishing: 2-3 articles per week
Goal: 100+ articles within 6 months

---

Generated by Auto-Agent Asset Generation System
EOF

print_success "Created README.md"

# Create initial homepage content
cat > "$WEBSITE_DIR/content/index.md" << EOF
# Welcome to $(echo "$WEBSITE_NAME" | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')

Your ultimate guide to $NICHE gaming!

## What We Offer

### 📝 In-Depth Reviews
Honest, comprehensive reviews of the best $NICHE games. We test every game thoroughly to help you make informed decisions.

### 📚 Expert Guides
Complete walkthroughs, tips, and strategies to help you master your favorite games.

### 🏆 Top Lists
Curated lists of the best $NICHE games across platforms, genres, and years.

### 📰 Latest News
Stay updated with the latest $NICHE gaming news, releases, and updates.

## Recent Articles

*Articles will appear here once content is generated*

## About Us

We're passionate $NICHE gamers dedicated to helping you discover amazing games and improve your gaming experience. All our content is carefully researched, tested, and written to provide genuine value.

---

**Ready to discover your next favorite game?** Browse our reviews, guides, and lists above!
EOF

print_success "Created homepage content"

# Create .gitignore
cat > "$WEBSITE_DIR/.gitignore" << EOF
# Dependencies
node_modules/
.pnp/
.pnp.js

# Build output
.next/
out/
build/
dist/

# Environment variables
.env
.env.local
.env.production

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# OS files
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/
*.swp
*.swo
EOF

print_success "Created .gitignore"

# Summary
print_header "Website Created Successfully!"
echo ""
echo "Website Location: $WEBSITE_DIR"
echo ""
echo "Next Steps:"
echo ""
echo "  1. Generate initial content (recommended: 20 articles):"
echo "     ${GREEN}./generate_content.sh $WEBSITE_NAME 20${NC}"
echo ""
echo "  2. Build the website:"
echo "     ${GREEN}./build_website.sh $WEBSITE_NAME${NC}"
echo ""
echo "  3. Deploy to hosting:"
echo "     ${GREEN}./deploy_website.sh $WEBSITE_NAME netlify${NC}"
echo ""
echo "For more information, see: $WEBSITE_DIR/README.md"
echo ""
print_success "Setup complete! 🎮"
